### ISSUE TITLE
Both Xcode and SPM?

### ISSUE THREAD

**Issue by mattmassicotte** [reddavis/Asynchrone#47]
Ok, so I screwed up in #45. I saw that SPM was the only installation method supported and stupidly did not notice the xcodeproj.

Typically when I use both it is because I need to build something that cannot be described with only a package. In this case, I'm not sure I understand why the Xcode project is needed. Can you help me understand?

**Comment by reddavis** [comment]
Yer it's a good point. The xcodeproj is left over from when I first made the lib and can now be removed. I've updated the project to just be a package. 🙌
